# Generated by Django 5.1.3 on 2024-12-18 06:55

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank='True', default='https://res.cloudinary.com/dxiawzgnz/image/upload/v1732632586/pfvvxablnkaeqmmbqeit.png', max_length=255, verbose_name='avatar')),
                ('cover_avatar', cloudinary.models.CloudinaryField(blank='True', default='https://res.cloudinary.com/dxiawzgnz/image/upload/v1733331571/hvyl33kneih3lsn1p9hp.png', max_length=255, verbose_name='cover')),
                ('account_status', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('Quản trị viên', 'ADMIN'), ('Giảng viên', 'LECTURER')], default='LECTURER', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_status',
            field=models.CharField(choices=[('Chờ xác nhận', 'PENDING'), ('Đã xác nhận', 'CONFIRMED'), ('Đã từ chối', 'REJECTED')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='AlumniAccount',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('alumni_account_code', models.CharField(max_length=50, unique=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Sociales.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
