# Generated by Django 5.1.3 on 2024-12-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0004_comment_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('post_survey_title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Sociales.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('question_content', models.TextField()),
                ('question_order', models.IntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('survey_question_type', models.CharField(choices=[('Chương trình đào tạo', 'TRAINING_PROGRAM'), ('Nhu cầu tuyển dụng', 'RECRUITMENT_NEEDS'), ('Thu nhập cựu sinh viên', 'ALUMNI_INCOME'), ('Tình hình việc làm', 'EMPLOYMENT_STATUS')], default='TRAINING_PROGRAM', max_length=50)),
                ('post_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='Sociales.postsurvey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
