# Generated by Django 5.1.3 on 2024-12-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0005_postsurvey_surveyquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(blank=True, max_length=10000, null=True)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sociales.surveyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_option_value', models.TextField()),
                ('question_option_order', models.IntegerField()),
                ('survey_answers', models.ManyToManyField(blank=True, to='Sociales.surveyanswer')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sociales.surveyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sociales.account')),
                ('post_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sociales.postsurvey')),
            ],
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sociales.surveyresponse'),
        ),
    ]
