# Generated by Django 5.1.3 on 2024-12-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0006_surveyanswer_surveyquestionoption_surveyresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('invitation_group_name', models.CharField(max_length=255)),
                ('accounts', models.ManyToManyField(blank=True, to='Sociales.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('event_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('accounts', models.ManyToManyField(blank=True, to='Sociales.account')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sociales.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
