# Generated by Django 5.1.3 on 2024-12-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0007_invitationgroup_postinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('received_message_date', models.DateTimeField(auto_now=True)),
                ('seen', models.BooleanField(default=False)),
                ('first_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user_room', to='Sociales.account')),
                ('second_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user_room', to='Sociales.account')),
            ],
            options={
                'unique_together': {('first_user', 'second_user')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=10000)),
                ('who_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sociales.account')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sociales.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
