# Generated by Django 5.1.3 on 2024-12-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0008_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Quản trị viên', 'ADMIN'), ('Giảng viên', 'LECTURER'), ('Cựu học sinh', 'ALUMNI')], default='LECTURER', max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
