# Generated by Django 5.1.3 on 2024-12-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0009_alter_account_role_alter_surveyanswer_answer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Quản trị viên', 'ADMIN'), ('Giảng viên', 'LECTURER')], default='LECTURER', max_length=50),
        ),
    ]
