# Generated by Django 5.1.3 on 2024-12-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0010_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
