# Generated by Django 5.1.3 on 2024-12-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0011_remove_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
