# Generated by Django 5.1.3 on 2024-12-24 16:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0012_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cover_avatar',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.RemoveField(
            model_name='alumniaccount',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='invitationgroup',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='postinvitation',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_status',
        ),
        migrations.AddField(
            model_name='alumniaccount',
            name='confirm_status',
            field=models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Confirmed', 'Đã xác nhận'), ('Rejected', 'Đã từ chối')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dxiawzgnz/image/upload/v1732632586/pfvvxablnkaeqmmbqeit.png', max_length=255, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dxiawzgnz/image/upload/v1733331571/hvyl33kneih3lsn1p9hp.png', max_length=255, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('User', 'Regular User'), ('Guest', 'Guest User')], default='User', max_length=50),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction',
            field=models.CharField(choices=[('Like', 'Like'), ('Haha', 'Haha'), ('Tym', 'Thả tym')], default='Like', max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey_question_type',
            field=models.CharField(choices=[('Training Program', 'Chương trình đào tạo'), ('Recruitment Needs', 'Nhu cầu tuyển dụng'), ('Alumni Income', 'Thu nhập cựu sinh viên'), ('Employment Status', 'Tình hình việc làm')], default='TRAINING_PROGRAM', max_length=50),
        ),
    ]
