# Generated by Django 5.1.3 on 2024-12-24 16:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0013_remove_account_account_status_remove_account_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover_avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dxiawzgnz/image/upload/v1732632586/pfvvxablnkaeqmmbqeit.png', max_length=255, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='account',
            name='cover_avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dxiawzgnz/image/upload/v1733331571/hvyl33kneih3lsn1p9hp.png', max_length=255, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Admin', 'Quản trị viên'), ('LECTURER', 'Giảng viên'), ('ALUMNI', 'Cựu sinh viên')], default='LECTURER', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Nam'), ('Female', 'Nữ')], default='Male', max_length=50),
        ),
    ]
