# Generated by Django 5.1.3 on 2025-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0015_account_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.BooleanField(default=True),
        ),
    ]
