# Generated by Django 5.1.3 on 2025-01-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0016_alter_account_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinvitation',
            name='accounts',
        ),
        migrations.AddField(
            model_name='postinvitation',
            name='accounts_alumni',
            field=models.ManyToManyField(blank=True, to='Sociales.alumniaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('account', 'post')},
        ),
    ]
