# Generated by Django 5.1.3 on 2025-01-21 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0018_user_password_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsurvey',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
