# Generated by Django 5.1.3 on 2025-01-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sociales', '0019_alter_postsurvey_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='notification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
