"""
Django settings for SocialApp project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dxiawzgnz',  # Cloud name của bạn
    'API_KEY': '916324835836949',  # API key của bạn
    'API_SECRET': 'it9HP_2TUJjIHLSshkbm0BYA5qE',  # API secret của bạn
    'UPLOAD_PRESET': 'socialapp',  # Đảm bảo bạn sử dụng đúng tên preset
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

HF_API_TOKEN = "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"
OPENAI_API_KEY = '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'

import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name="dxiawzgnz",
    api_key="916324835836949",
    api_secret="it9HP_2TUJjIHLSshkbm0BYA5qE",

    secure=True,

)
DEFAULT_FILE_STORAGE = 'cloudinary.storage.MediaCloudinaryStorage'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q+iorsbp#(ic55v1!*76i*sk7-esi3%#i&)dtiwn!ozuj08d@-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#Xem lại
ALLOWED_HOSTS = ['socialapp130124.pythonanywhere.com']


#Debug file
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'celery': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '%s/SocialApp/celery_task_log.log' % BASE_DIR,
            # 'filename': 'D:/celery.log',
        },
    },
    'loggers': {
        'celery': {
            'handlers': ['celery'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
CELERY_IMPORTS = ('Sociales.tasks',)
# Đặt danh sách các tasks mà Celery sẽ tìm kiếm và đăng ký
# Message Broker (Tiện có redis
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_EXTENDED = True
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# Application definition



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'theanhtran13012004@gmail.com'
EMAIL_HOST_PASSWORD =  'kmui vkff bpwd wyke'
EMAIL_USE_TLS = True  # or False if not using TLS/SSL
DEFAULT_FROM_EMAIL = 'theanhtran13012004@gmail.com'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Sociales.apps.SocialesConfig',
    'cloudinary',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg', #Swagger UI
    'oauth2_provider',
    'cloudinary_storage', #đường dẫn cloud mặc định
    'celery',
    'django_celery_results',
    'django_celery_beat',
    'channels', #Chat tg thực trong consumers
    'channels_redis' #Lưu tru thong tin chat
#Côi còn COR nữa
]


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
import pymysql
pymysql.install_as_MySQLdb()
AUTH_USER_MODEL = 'Sociales.User'
CKEDITOR_UPLOAD_PATH = "images/tenluutru/"

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',

    ),
        'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ]
}

#Thêm vào để setup lại hiệu lực token
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 86400000,  #Một ngày -> Đã fix thành 10 ngày

}


# ClIENT_ID = 33NUWzTqhQH89h7dgm3sXYDK5tA0VIBAcxqFGaY0
# Client secret = 7rbHXYJsVUiIpL2cvNQeFS18s5BeTvqcre6ugsuwQVGR1K3w9yBLIICAvks7ASW16VxlxT6F7bHWyB9CUJNUQdImaSHQfXRFAGEVCJgLR7O2YVoBmbkROWJh4iiyNdTd



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


ROOT_URLCONF = 'SocialApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SocialApp.wsgi.application'
#Phân trang trên swagger
# REST_FRAMEWORK = {
#
# 'DEFAULT_PAGINATION_CLASS':
# 'rest_framework.pagination.PageNumberPagination',
# 'PAGE_SIZE': 3
#
#
# }


#Redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis chạy tại localhost trên cổng 6379
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'socialapp130124$socialdb',
        'USER': 'socialapp130124',
        'PASSWORD': 'tta130124',
        'HOST': 'socialapp130124.mysql.pythonanywhere-services.com'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
